task:
  name: FreeBSD
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --installdeps .
    - perl Makefile.PL
    - make
    - make test
