task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0-snap
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --installdeps .
    - perl Makefile.PL
    - make
    - make test

task:
  name: MacOS
  osx_instance:
    image: catalina-xcode-12.0
  test_script:
    - curl -L https://install.perlbrew.pl | bash
    - source ~/perl5/perlbrew/etc/bashrc
    - perlbrew init
    - perlbrew install -v perl-5.30.3
    - perlbrew switch perl-5.30.3
    - perlbrew install-cpanm -f
    - perl -v
    - cpanm TAP::Harness::Env
    - cpanm --installdeps . || cat /Users/anka/.cpanm/work/*/build.log
    - perl Makefile.PL
    - make
    - make test
